server:
  port: 5000
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/stock
  jackson:
    time-zone: GMT+8

#logging:
#  config: classpath:logging-spring.xml




